name: Sync Files to Releases

on:
  push:
    paths:
      - 'backend/data/**'
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd backend
        npm install @octokit/rest
        
    - name: Sync files to releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd backend
        node sync-to-releases.js 